spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://lallah.db.elephantsql.com:5432/qcmpbadl
        username: qcmpbadl
        password: zlJZhv2FfZJdEX41Rxcr3b4bCS6b3Lko
    sql:
        init:
            mode: always
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update

jwt:
    secret: 309583049sldfjsldkfjsldkfjsldf9203480293